GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFBQSIsImlkIjoiNjVjMzNiNTM3ZjI5MDY4MGM2MGY1YzE3IiwiaWF0IjoxNzA3MjkzNTM4fQ.VbNP_QafG9JS6PW0mk_HNyDelLiLijLCeDLgFjwP9pU

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFBQSIsImlkIjoiNjVjMzNiNTM3ZjI5MDY4MGM2MGY1YzE3IiwiaWF0IjoxNzA3MjkzNTM4fQ.VbNP_QafG9JS6PW0mk_HNyDelLiLijLCeDLgFjwP9pU

{
    "title": "PLEASE DELETE 5",
    "author": "AAA",
    "url": "https://www.google.com",
    "likes": 27
}

###
PUT http://localhost:3003/api/blogs/65bfa31c5ae0ac812bfce797
content-type: application/json

{
    "likes": 232325
}

###
DELETE http://localhost:3003/api/blogs/65c33c5a0599b60054fdaeeb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFBQSIsImlkIjoiNjVjMzNiNTM3ZjI5MDY4MGM2MGY1YzE3IiwiaWF0IjoxNzA3MjkzNTM4fQ.VbNP_QafG9JS6PW0mk_HNyDelLiLijLCeDLgFjwP9pU

###
POST http://localhost:3003/api/blogs/65c493dea1880a77323c6f88/comments
content-type: application/json

{
    "content": "Third comment!"
} 