GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "asdgeweg",
    "name": "Mathias",
    "password": "a23"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "asdgeweg",
    "password": "a23"
}